load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "recruiting_mapper_test",
    srcs = ["recruiting_mapper_test.py"],
    deps = ["//backend/recruiting"],
)

py_test(
    name = "job_service_test",
    srcs = ["job_service_test.py"],
    deps = ["//backend/recruiting"],
)

py_test(
    name = "application_service_submit_test",
    srcs = ["application_service_submit_test.py"],
    deps = ["//backend/recruiting"],
)

py_test(
    name = "application_service_view_test",
    srcs = ["application_service_view_test.py"],
    deps = ["//backend/recruiting"],
)

py_test(
    name = "application_service_advance_test",
    srcs = ["application_service_advance_test.py"],
    deps = ["//backend/recruiting"],
)
