load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "application_entity_test",
    srcs = ["application_entity_test.py"],
    deps = ["//backend/common:recruiting_enums", "//backend/entity:entities"],
)
