# Read-only PostgreSQL users for ad-hoc query access on prod.
# Each user is fully TF-managed: role + grants + default privileges +
# statement_timeout. Password is generated by Terraform and exposed only
# via a `sensitive` output, never written to disk in plain form.
#
# Rotation: `terraform taint random_password.daisy && terraform apply`.
# Revocation: delete the resources below and apply.

resource "random_password" "daisy" {
  length  = 40
  special = false
}

resource "postgresql_role" "daisy" {
  name     = "readonly_daisyisadaisy"
  login    = true
  password = random_password.daisy.result

  # 60s — value is in milliseconds. Keeps a runaway analytical query
  # from pinning a Neon compute.
  statement_timeout = 60000
}

resource "postgresql_grant" "daisy_db_connect" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "daisy_schema_usage" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  schema      = "public"
  object_type = "schema"
  privileges  = ["USAGE"]
}

resource "postgresql_grant" "daisy_table_select" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  schema      = "public"
  object_type = "table"
  objects     = []
  privileges  = ["SELECT"]
}

resource "postgresql_grant" "daisy_sequence_select" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  schema      = "public"
  object_type = "sequence"
  objects     = []
  privileges  = ["SELECT"]
}

# Future tables/sequences created by the owner role (e.g. via Alembic
# migrations) automatically get SELECT for daisy. Without this, every
# new migration silently makes a table invisible to her.
resource "postgresql_default_privileges" "daisy_future_tables" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  owner       = module.purrf_instance.neon_owner_role_name
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}

resource "postgresql_default_privileges" "daisy_future_sequences" {
  database    = module.purrf_instance.neon_db_name
  role        = postgresql_role.daisy.name
  owner       = module.purrf_instance.neon_owner_role_name
  schema      = "public"
  object_type = "sequence"
  privileges  = ["SELECT"]
}
