load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "google_chat_message_store_test",
    srcs = ["google_chat_message_store_test.py"],
    deps = [
        "//src/utils:google_chat_message_store",
    ],
)

py_test(
    name = "google_chat_utils_test",
    srcs = ["google_chat_utils_test.py"],
    deps = [
        "//src/utils:google_chat_utils",
    ],
)
