load("@rules_python//python:defs.bzl", "py_library", "py_test")

py_test(
    name = "profile_mapper_test",
    srcs = ["profile_mapper_test.py"],
    deps = [
        "//backend/profile:profile_mapper",
    ],
)
