import os

LOG_LEVEL = "LOG_LEVEL"
USER_EMAIL = "USER_EMAIL"
SERVICE_ACCOUNT_EMAIL = "SERVICE_ACCOUNT_EMAIL"
ADMIN_EMAIL = "ADMIN_EMAIL"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_PASSWORD = "REDIS_PASSWORD"

# Used to initialize the Gerrit client.
GERRIT_URL = "GERRIT_URL"
GERRIT_USER = "GERRIT_USER"
GERRIT_HTTP_PASS = "GERRIT_HTTP_PASS"

# Used to create gerrit webhooks
GERRIT_WEBHOOK_REMOTE_NAME = "GERRIT_WEBHOOK_REMOTE_NAME"
GERRIT_WEBHOOK_TARGET_URL = "GERRIT_WEBHOOK_TARGET_URL"
GERRIT_WEBHOOK_EVENTS = "GERRIT_WEBHOOK_EVENTS"
GERRIT_WEBHOOK_PROJECT = "GERRIT_WEBHOOK_PROJECT"

AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
AZURE_TENANT_ID = "AZURE_TENANT_ID"

JIRA_SERVER = "JIRA_SERVER"
JIRA_USER = "JIRA_USER"
JIRA_PASSWORD = "JIRA_PASSWORD"

MICROSOFT_ADMIN_LDAP = "MICROSOFT_ADMIN_LDAP"
MICROSOFT_USER_LDAP = "MICROSOFT_USER_LDAP"

LAUNCHDARKLY_SDK_KEY = "LAUNCHDARKLY_SDK_KEY"

PUBSUB_PROJECT_ID = "PUBSUB_PROJECT_ID"
MICROSOFT_SUBSCRIPTION_ID = "MICROSOFT_SUBSCRIPTION_ID"
GOOGLE_CHAT_SUBSCRIPTION_ID = "GOOGLE_CHAT_SUBSCRIPTION_ID"
GERRIT_SUBSCRIPTION_ID = "GERRIT_SUBSCRIPTION_ID"

DATABASE_URL = os.getenv("DATABASE_URL")

CF_TEAM_DOMAIN = os.getenv("CF_TEAM_DOMAIN")
CF_AUD_TAG = os.getenv("CF_AUD_TAG")
GOOGLE_AUDIENCE = os.getenv("GOOGLE_AUDIENCE")

TAILSCALE_PROXY = "TAILSCALE_PROXY"

MENTORSHIP_MENTOR_ONBOARDING_LINK = "MENTORSHIP_MENTOR_ONBOARDING_LINK"
MENTORSHIP_MENTEE_ONBOARDING_LINK = "MENTORSHIP_MENTEE_ONBOARDING_LINK"

RESUME_BUCKET = "RESUME_BUCKET"

# Auth0 multi-IdP email OTP / account-link flow.
# Passwordless app drives the OTP send + verify; the M2M app holds Management
# API credentials for identity linking and app_metadata writes.
AUTH0_TENANT_DOMAIN = "AUTH0_TENANT_DOMAIN"
AUTH0_PASSWORDLESS_CLIENT_ID = "AUTH0_PASSWORDLESS_CLIENT_ID"
AUTH0_PASSWORDLESS_CLIENT_SECRET = "AUTH0_PASSWORDLESS_CLIENT_SECRET"
AUTH0_M2M_CLIENT_ID = "AUTH0_M2M_CLIENT_ID"
AUTH0_M2M_CLIENT_SECRET = "AUTH0_M2M_CLIENT_SECRET"
AUTH0_M2M_AUDIENCE = "AUTH0_M2M_AUDIENCE"

# HMAC secret signing the short-lived state JWT that ties an OTP verify back to
# the session that initiated it (CSRF guard).
EMAIL_OTP_STATE_JWT_SECRET = "EMAIL_OTP_STATE_JWT_SECRET"
