import { useEffect } from "react";
import TimezoneSelect from "react-timezone-select";
import { Check } from "lucide-react";
import timezones from "@/constants/Timezones";
import { defaultTimezoneSelectStyles } from "@/components/common/TimezoneSelector.styles";

/**
 * Timezone selector backed by the shared timezones list in @/constants/Timezones.
 *
 * Includes default styling via {@link defaultTimezoneSelectStyles}.
 *
 * To override specific style keys, import {@link defaultTimezoneSelectStyles},
 * spread it, and pass the modified object to the `styles` prop.
 * Alternatively, pass a new object to completely replace all default styles.
 *
 * @param {string} props.value - IANA timezone string (e.g. "America/New_York"). The displayed
 *   label is auto-generated by react-timezone-select as "(GMT{offset}) {label}", where the label
 *   comes from @/constants/Timezones and the offset is calculated from the IANA key at render time
 *   (e.g. "(GMT-4:00) Eastern Time (US & Canada)").
 * @param {function} props.onChange - Called with the react-select option object {value, label}
 * @param {"value"|"key"} [props.labelSource="value"] - Controls the label displayed in the
 *   dropdown and control. "value" shows the label from @/constants/Timezones (e.g. "Eastern Time
 *   (US & Canada)"); "key" shows the IANA key (e.g. "America/New_York").
 */
export default function TimezoneSelector({
  value,
  onChange,
  labelSource = "value",
  styles = defaultTimezoneSelectStyles,
  menuPlacement = "auto",
  ...props
}) {
  // Intercept scroll/touch events globally in the capture phase to bypass Dialog scroll locks
  useEffect(() => {
    const handleScroll = (e) => {
      // Locate the portal-rendered dropdown menu in the DOM
      const menuEl = document.querySelector(".react-select__menu");
      if (menuEl && menuEl.contains(e.target)) {
        e.stopPropagation();
      }
    };

    document.addEventListener("wheel", handleScroll, {
      capture: true,
      passive: false,
    });
    document.addEventListener("touchmove", handleScroll, {
      capture: true,
      passive: false,
    });

    return () => {
      document.removeEventListener("wheel", handleScroll, { capture: true });
      document.removeEventListener("touchmove", handleScroll, {
        capture: true,
      });
    };
  }, []);

  const enhancedStyles = {
    ...styles,
    singleValue: (provided, state) => {
      const base = styles?.singleValue
        ? styles.singleValue(provided, state)
        : provided;
      return {
        ...base,
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
      };
    },

    menu: (provided, state) => {
      const base = styles?.menu ? styles.menu(provided, state) : provided;
      return {
        ...base,
        overflow: "hidden",
        paddingBottom: "4px",
        zIndex: 9999,
      };
    },

    menuList: (provided, state) => {
      const base = styles?.menuList
        ? styles.menuList(provided, state)
        : provided;
      return {
        ...base,
        maxHeight: "170px",
        paddingBottom: "16px",
        overscrollBehavior: "contain",
      };
    },
  };

  return (
    <TimezoneSelect
      {...props}
      value={value}
      onChange={onChange}
      timezones={timezones}
      menuPlacement={menuPlacement}
      menuPortalTarget={typeof window !== "undefined" ? document.body : null}
      classNamePrefix="react-select"
      captureMenuScroll={true}
      lockMenuScroll={false}
      menuShouldScrollIntoView={true}
      formatOptionLabel={(option, { context, selectValue } = {}) => {
        if (typeof option === "string") return option;
        const label = labelSource === "key" ? option.value : option.label;
        if (context === "value") return label;
        const isSelected = selectValue?.some((v) => v.value === option.value);
        return (
          <div className="flex w-full items-center justify-between gap-2">
            <span className="truncate">{label}</span>
            <span className="flex size-4 shrink-0 items-center justify-center">
              {isSelected && <Check className="size-4 pointer-events-none" />}
            </span>
          </div>
        );
      }}
      styles={enhancedStyles}
    />
  );
}
