export const ROUTE_PATHS = {
  ROOT: "/",
  DASHBOARD: "/dashboard",
  DATASEARCH: "/datasearch",
  PROFILE: "/profile",
  PERSONAL_DASHBOARD: "/dashboard/me",
  ACCESS_DENIED: "/access-denied",
  MENTORSHIP_MANAGEMENT: "/mentorship-management",
  VERIFY_REQUIRED: "/verify-required",
  SIGN_IN_SECURITY: "/settings/sign-in",
  RECRUITING_ADMIN: "/recruiting/admin",
  RECRUITING_APPLY: "/recruiting/apply/:jobId",
  RECRUITING_SCREENING_INDEX: "/recruiting/screening",
  RECRUITING_SCREENING: "/recruiting/screening/:jobId",
};
