export const ROUTE_PATHS = {
  ROOT: "/",
  DASHBOARD: "/dashboard",
  DATASEARCH: "/datasearch",
  PROFILE: "/profile",
  PERSONAL_DASHBOARD: "/dashboard/me",
  ACCESS_DENIED: "/access-denied",
  MENTORSHIP_MANAGEMENT: "/mentorship-management",
  VERIFY_REQUIRED: "/verify-required",
  SIGN_IN_SECURITY: "/settings/sign-in",
  ADMIN_USERS: "/admin/users",
  RECRUITING_POSTINGS: "/recruiting/postings",
  RECRUITING_POSTING_NEW: "/recruiting/postings/new",
  RECRUITING_POSTING_EDIT: (jobId) => `/recruiting/postings/${jobId}/edit`,
  RECRUITING_REVIEWS: "/recruiting/reviews",
};
