# Expose the computed domains generated by the purrf_instance module.
output "prod_domains" {
  value = module.purrf_instance.computed_domains
}

# Expose the resource name prefix used by this module.
output "resource_prefix" {
  value = module.purrf_instance.resource_prefix
}

output "redis_endpoint" {
  value = module.purrf_instance.redis_endpoint
}

output "redis_password" {
  value     = module.purrf_instance.redis_password
  sensitive = true
}

output "redis_port" {
  value = tostring(module.purrf_instance.redis_port)
}

output "auth0_client_id" {
  value = module.purrf_instance.auth0_client_id
}

output "neon_project_id" {
  value = module.purrf_instance.neon_project_id
}

output "neon_default_branch_id" {
  value = module.purrf_instance.neon_default_branch_id
}

output "neon_database_owner" {
  value = module.purrf_instance.neon_database_owner
}

output "default_gsa_account" {
  value = module.purrf_instance.default_account
}