# Expose the computed domains generated by the purrf_instance module.
output "test_domains" {
  value = module.purrf_instance.computed_domains
}

# Expose the resource name prefix used by this module.
output "resource_prefix" {
  value = module.purrf_instance.resource_prefix
}

output "redis_endpoint" {
  value = module.purrf_instance.redis_endpoint
}

output "auth0_client_id" {
  value = module.purrf_instance.auth0_client_id
}

output "neon_project_id" {
  value = module.purrf_instance.neon_project_id
}

output "neon_default_branch_id" {
  value = module.purrf_instance.neon_default_branch_id
}

output "neon_database_user" {
  value = module.purrf_instance.neon_database_user
}