"""drop cc_addresses from email_message

Revision ID: 051306857625
Revises: bb4ebd00c402
Create Date: 2026-10-03 02:22:28.018907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "051306857625"
down_revision: Union[str, Sequence[str], None] = "bb4ebd00c402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_message", "cc_addresses")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_message",
        sa.Column("cc_addresses", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
