"""Add email_thread and email_message tables

Revision ID: 156f56629f81
Revises: 82498a573699
Create Date: 2026-07-23 04:52:27.311430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "156f56629f81"
down_revision: Union[str, Sequence[str], None] = "82498a573699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_thread",
        sa.Column("thread_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=True),
        sa.Column("context_type", sa.String(), nullable=False),
        sa.Column("context_id", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_email_thread_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thread_id", name=op.f("pk_email_thread")),
        sa.UniqueConstraint(
            "gmail_thread_id", name=op.f("uq_email_thread_gmail_thread_id")
        ),
    )
    op.create_index(
        "ix_email_thread_context",
        "email_thread",
        ["context_type", "context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_thread_user_id"), "email_thread", ["user_id"], unique=False
    )
    op.create_table(
        "email_message",
        sa.Column("message_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=255), nullable=False),
        sa.Column("rfc822_message_id", sa.String(length=998), nullable=True),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("from_address", sa.String(length=255), nullable=True),
        sa.Column("to_addresses", sa.Text(), nullable=True),
        sa.Column("cc_addresses", sa.Text(), nullable=True),
        sa.Column("subject", sa.String(length=998), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("sent_by_user_id", sa.Integer(), nullable=True),
        sa.Column("gmail_internal_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sent_by_user_id"],
            ["users.user_id"],
            name=op.f("fk_email_message_sent_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_thread.thread_id"],
            name=op.f("fk_email_message_thread_id_email_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_email_message")),
        sa.UniqueConstraint(
            "gmail_message_id", name=op.f("uq_email_message_gmail_message_id")
        ),
    )
    op.create_index(
        op.f("ix_email_message_gmail_internal_date"),
        "email_message",
        ["gmail_internal_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_message_thread_id"), "email_message", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_message_thread_id"), table_name="email_message")
    op.drop_index(
        op.f("ix_email_message_gmail_internal_date"), table_name="email_message"
    )
    op.drop_table("email_message")
    op.drop_index(op.f("ix_email_thread_user_id"), table_name="email_thread")
    op.drop_index("ix_email_thread_context", table_name="email_thread")
    op.drop_table("email_thread")
    # ### end Alembic commands ###
