"""add mentorship meeting table

Revision ID: 1677977acf62
Revises: c82e1d48e253
Create Date: 2026-07-31 08:18:32.157870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1677977acf62'
down_revision: Union[str, Sequence[str], None] = 'c82e1d48e253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('manual', 'google', 'legacy', name='meeting_source_enum').create(op.get_bind())
    op.create_table('mentorship_meeting',
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('source', postgresql.ENUM('manual', 'google', 'legacy', name='meeting_source_enum', create_type=False), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meet_link', sa.String(), nullable=True),
    sa.Column('google_meeting_code', sa.String(), nullable=True),
    sa.Column('entry_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('absent_user_id', sa.Integer(), nullable=True),
    sa.Column('late_user_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('has_unknown_absent', sa.Boolean(), nullable=True),
    sa.Column('has_unknown_late', sa.Boolean(), nullable=True),
    sa.Column('has_insufficient_duration', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source = 'google' OR (meet_link IS NULL AND google_meeting_code IS NULL AND entry_points IS NULL AND absent_user_id IS NULL AND late_user_ids IS NULL AND has_unknown_absent IS NULL AND has_unknown_late IS NULL AND has_insufficient_duration IS NULL AND last_sync_at IS NULL)", name=op.f('ck_mentorship_meeting_google_fields')),
    sa.CheckConstraint("source = 'legacy' OR (start_datetime IS NOT NULL AND end_datetime IS NOT NULL AND end_datetime > start_datetime)", name=op.f('ck_mentorship_meeting_times')),
    sa.ForeignKeyConstraint(['pair_id'], ['mentorship_pairs.pair_id'], name=op.f('fk_mentorship_meeting_pair_id_mentorship_pairs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_mentorship_meeting'))
    )
    op.create_index('ix_mentorship_meeting_google_code', 'mentorship_meeting', ['google_meeting_code'], unique=False, postgresql_where=sa.text('google_meeting_code IS NOT NULL'))
    op.create_index('ix_mentorship_meeting_pair_start', 'mentorship_meeting', ['pair_id', 'start_datetime'], unique=False)
    op.create_index('ix_mentorship_meeting_pending', 'mentorship_meeting', ['pair_id'], unique=False, postgresql_where=sa.text('is_completed = false'))
    # ### end Alembic commands ###

    # --- Data migration: move mentorship_pairs.meeting_log into rows. ---
    # meeting_log is deliberately left in place (read-only escape hatch for
    # one release) and mentorship_pairs.completed_count is never touched --
    # the legacy rows below exist to make that column verifiable, not to
    # replace it.

    # manual meetings: meeting_log->'meeting_time_list'
    op.execute("""
        INSERT INTO mentorship_meeting (
            meeting_id, pair_id, source,
            start_datetime, end_datetime, is_completed, created_datetime
        )
        SELECT
            e->>'meeting_id',
            p.pair_id,
            'manual'::meeting_source_enum,
            (e->>'start_datetime')::timestamptz,
            (e->>'end_datetime')::timestamptz,
            COALESCE((e->>'is_completed')::boolean, FALSE),
            (e->>'created_datetime')::timestamptz
        FROM mentorship_pairs p
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE WHEN jsonb_typeof(p.meeting_log->'meeting_time_list') = 'array'
                 THEN p.meeting_log->'meeting_time_list' ELSE '[]'::jsonb END
        ) AS e
    """)

    # google meetings: meeting_log->'google_meetings'
    op.execute("""
        INSERT INTO mentorship_meeting (
            meeting_id, pair_id, source,
            start_datetime, end_datetime, is_completed, created_datetime,
            meet_link, google_meeting_code, entry_points,
            absent_user_id, late_user_ids,
            has_unknown_absent, has_unknown_late,
            has_insufficient_duration, last_sync_at
        )
        SELECT
            e->>'meeting_id',
            p.pair_id,
            'google'::meeting_source_enum,
            (e->>'start_datetime')::timestamptz,
            (e->>'end_datetime')::timestamptz,
            COALESCE((e->>'is_completed')::boolean, FALSE),
            (e->>'created_datetime')::timestamptz,
            NULLIF(e->>'meet_link', ''),
            NULLIF(e->>'conference_id', ''),
            CASE WHEN jsonb_typeof(e->'entry_points') = 'array'
                 THEN e->'entry_points' END,
            (e->>'absent_user_id')::int,
            CASE WHEN jsonb_typeof(e->'late_user_id') = 'array'
                 THEN ARRAY(
                     SELECT jsonb_array_elements_text(e->'late_user_id')::int
                 ) END,
            (e->>'has_unknown_absent')::boolean,
            (e->>'has_unknown_late')::boolean,
            (e->>'has_insufficient_duration')::boolean,
            (e->>'last_sync_at')::timestamptz
        FROM mentorship_pairs p
        CROSS JOIN LATERAL jsonb_array_elements(
            CASE WHEN jsonb_typeof(p.meeting_log->'google_meetings') = 'array'
                 THEN p.meeting_log->'google_meetings' ELSE '[]'::jsonb END
        ) AS e
    """)

    # legacy rows: fabricate exactly enough rows (no times) to make each
    # pair's is_completed row count catch up to completed_count.
    #
    # The criterion is the SHORTFALL (completed_count minus the completed
    # rows the two INSERTs above just created for this pair), not "this pair
    # has no meeting_log arrays". Those are not the same thing:
    #   - meeting_log = {"google_meetings": []} with completed_count > 0:
    #     jsonb_typeof is 'array', so a "no arrays present" criterion skips
    #     the pair entirely, while the google INSERT expands the empty array
    #     to zero rows -- positive count, zero rows, invariant broken.
    #   - an array is present but its completed-entry count differs from
    #     completed_count (known counter drift from the old four-writers
    #     problem) -- also not "no arrays present", also needs a top-up.
    # Counting actual rows already inserted for this pair, rather than
    # inspecting meeting_log's shape, makes
    #   completed_count = COUNT(*) WHERE pair_id = p.pair_id AND is_completed
    # hold by construction regardless of empty arrays or counter drift.
    # generate_series(1, n) with n <= 0 yields zero rows (verified empirically
    # -- see task-2-report.md), so no separate WHERE guard is needed here.
    op.execute("""
        INSERT INTO mentorship_meeting (
            meeting_id, pair_id, source, is_completed, created_datetime
        )
        SELECT
            'legacy-' || p.pair_id || '-' || n,
            p.pair_id,
            'legacy'::meeting_source_enum,
            TRUE,
            now()
        FROM mentorship_pairs p
        CROSS JOIN LATERAL generate_series(
            1,
            p.completed_count - (
                SELECT count(*) FROM mentorship_meeting m
                WHERE m.pair_id = p.pair_id AND m.is_completed
            )
        ) AS n
    """)

    # The shortfall INSERT above can only ever ADD rows, so it cannot fix a
    # pair whose completed_count is LOWER than its number of completed
    # entries. That case would otherwise migrate "successfully" with the
    # invariant broken and nothing logged. Assert it here instead: the whole
    # revision is one transaction, so this rolls everything back.
    op.execute("""
        DO $$
        DECLARE
            mismatched int;
        BEGIN
            SELECT count(*) INTO mismatched
            FROM mentorship_pairs p
            WHERE p.completed_count <> (
                SELECT count(*) FROM mentorship_meeting m
                WHERE m.pair_id = p.pair_id AND m.is_completed
            );
            IF mismatched > 0 THEN
                RAISE EXCEPTION
                    'mentorship_meeting migration would leave % pair(s) whose '
                    'completed_count does not match their completed meeting '
                    'rows; reconcile mentorship_pairs.completed_count first',
                    mismatched;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentorship_meeting_pending', table_name='mentorship_meeting', postgresql_where=sa.text('is_completed = false'))
    op.drop_index('ix_mentorship_meeting_pair_start', table_name='mentorship_meeting')
    op.drop_index('ix_mentorship_meeting_google_code', table_name='mentorship_meeting', postgresql_where=sa.text('google_meeting_code IS NOT NULL'))
    op.drop_table('mentorship_meeting')
    sa.Enum('manual', 'google', 'legacy', name='meeting_source_enum').drop(op.get_bind())
    # ### end Alembic commands ###
