"""Add a domain-neutral event table and rework notification

Revision ID: 1eed2204a642
Revises: d3f81b0a6c47
Create Date: 2026-08-07 07:43:14.090025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1eed2204a642"
down_revision: Union[str, Sequence[str], None] = "d3f81b0a6c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "pending",
        "sending",
        "sent",
        "failed",
        "expired",
        name="notification_status_enum",
    ).create(op.get_bind())
    op.create_table(
        "event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.user_id"],
            name=op.f("fk_event_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_event")),
    )
    op.create_index(
        "ix_event_subject", "event", ["subject_type", "subject_id"], unique=False
    )
    op.add_column("notification", sa.Column("event_id", sa.Integer(), nullable=True))
    op.add_column(
        "notification",
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "sending",
                "sent",
                "failed",
                "expired",
                name="notification_status_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "notification",
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_notification_event_id"), "notification", ["event_id"], unique=False
    )
    op.create_index(
        "ix_notification_pending",
        "notification",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_user_undismissed",
        "notification",
        ["user_id", "dismissed_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_notification_event_id_event"),
        "notification",
        "event",
        ["event_id"],
        ["event_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_notification_event_id_event"), "notification", type_="foreignkey"
    )
    op.drop_index("ix_notification_user_undismissed", table_name="notification")
    op.drop_index("ix_notification_pending", table_name="notification")
    op.drop_index(op.f("ix_notification_event_id"), table_name="notification")
    op.drop_column("notification", "dismissed_at")
    op.drop_column("notification", "claimed_at")
    op.drop_column("notification", "status")
    op.drop_column("notification", "event_id")
    op.drop_index("ix_event_subject", table_name="event")
    op.drop_table("event")
    sa.Enum(
        "pending",
        "sending",
        "sent",
        "failed",
        "expired",
        name="notification_status_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
