"""add notified note tag and notification stage

Revision ID: 24dfd0377a51
Revises: f2b3354b3118
Create Date: 2026-10-10 08:41:15.857900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "24dfd0377a51"
down_revision: Union[str, Sequence[str], None] = "f2b3354b3118"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mentorship_participant_note",
        sa.Column("notification_stage", sa.String(length=32), nullable=True),
    )
    op.sync_enum_values(
        "public",
        "participant_note_tag_enum",
        ["status_change", "matching_exemption", "no_show", "red_flag", "notified"],
        [
            TableReference(
                table_schema="public",
                table_name="mentorship_participant_note",
                column_name="tag",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "participant_note_tag_enum",
        ["status_change", "matching_exemption", "no_show", "red_flag"],
        [
            TableReference(
                table_schema="public",
                table_name="mentorship_participant_note",
                column_name="tag",
            )
        ],
        enum_values_to_rename=[],
    )
    op.drop_column("mentorship_participant_note", "notification_stage")
    # ### end Alembic commands ###
