"""Drop the legacy notification model

Revision ID: 2ec9de850734
Revises: 8cb4d2319db5
Create Date: 2026-08-08 05:33:25.849511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ec9de850734"
down_revision: Union[str, Sequence[str], None] = "8cb4d2319db5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_activity_application_id"),
        table_name="application_activity",
    )
    op.drop_table("application_activity")
    op.drop_index(op.f("ix_job_activity_job_id"), table_name="job_activity")
    op.drop_table("job_activity")
    # Rows written before the event model exist only in a database that ran
    # the expand migration and was then written to by the old path. They
    # cannot be rendered once `type` is gone, and the column below cannot go
    # NOT NULL while they are here.
    op.execute("DELETE FROM notification WHERE event_id IS NULL")
    op.alter_column(
        "notification", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_notification_application_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_job_id"), table_name="notification")
    op.drop_constraint(
        op.f("fk_notification_application_id_application"),
        "notification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_notification_job_review_id_job_review"),
        "notification",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_notification_actor_user_id_users"), "notification", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_notification_job_id_job"), "notification", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_notification_comment_id_application_comment"),
        "notification",
        type_="foreignkey",
    )
    op.drop_column("notification", "comment_id")
    op.drop_column("notification", "round")
    op.drop_column("notification", "email_sent_at")
    op.drop_column("notification", "actor_user_id")
    op.drop_column("notification", "job_review_id")
    op.drop_column("notification", "type")
    op.drop_column("notification", "job_id")
    op.drop_column("notification", "application_id")
    sa.Enum(
        "assigned_to_evaluate",
        "mentioned",
        "job_review_requested",
        "job_review_approved",
        "job_review_rejected",
        "application_submitted",
        "application_auto_rejected",
        "application_auto_hired",
        name="notification_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "assigned_to_evaluate",
        "mentioned",
        "job_review_requested",
        "job_review_approved",
        "job_review_rejected",
        "application_submitted",
        "application_auto_rejected",
        "application_auto_hired",
        name="notification_type_enum",
    ).create(op.get_bind())
    op.add_column(
        "notification",
        sa.Column("application_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column(
            "type",
            postgresql.ENUM(
                "assigned_to_evaluate",
                "mentioned",
                "job_review_requested",
                "job_review_approved",
                "job_review_rejected",
                "application_submitted",
                "application_auto_rejected",
                "application_auto_hired",
                name="notification_type_enum",
                create_type=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notification",
        sa.Column("job_review_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column("actor_user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column(
            "email_sent_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notification",
        sa.Column("round", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification",
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_notification_comment_id_application_comment"),
        "notification",
        "application_comment",
        ["comment_id"],
        ["comment_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_notification_job_id_job"),
        "notification",
        "job",
        ["job_id"],
        ["job_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_notification_actor_user_id_users"),
        "notification",
        "users",
        ["actor_user_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_notification_job_review_id_job_review"),
        "notification",
        "job_review",
        ["job_review_id"],
        ["review_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_notification_application_id_application"),
        "notification",
        "application",
        ["application_id"],
        ["application_id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_notification_job_id"), "notification", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_application_id"),
        "notification",
        ["application_id"],
        unique=False,
    )
    # Rows written before the event model exist only in a database that ran
    # the expand migration and was then written to by the old path. They
    # cannot be rendered once `type` is gone, and the column below cannot go
    # NOT NULL while they are here.
    op.execute("DELETE FROM notification WHERE event_id IS NULL")
    op.alter_column(
        "notification", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_table(
        "job_activity",
        sa.Column("activity_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("actor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.user_id"],
            name=op.f("fk_job_activity_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.job_id"],
            name=op.f("fk_job_activity_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("activity_id", name=op.f("pk_job_activity")),
    )
    op.create_index(
        op.f("ix_job_activity_job_id"), "job_activity", ["job_id"], unique=False
    )
    op.create_table(
        "application_activity",
        sa.Column("activity_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("actor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.user_id"],
            name=op.f("fk_application_activity_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
            name=op.f("fk_application_activity_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("activity_id", name=op.f("pk_application_activity")),
    )
    op.create_index(
        op.f("ix_application_activity_application_id"),
        "application_activity",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###
