"""add application_comment table

Revision ID: 3186f77c39e6
Revises: 5b8efe125dac
Create Date: 2026-07-07 07:28:21.084238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3186f77c39e6"
down_revision: Union[str, Sequence[str], None] = "5b8efe125dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_comment",
        sa.Column("comment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
            name=op.f("fk_application_comment_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.user_id"],
            name=op.f("fk_application_comment_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("comment_id", name=op.f("pk_application_comment")),
    )
    op.create_index(
        op.f("ix_application_comment_application_id"),
        "application_comment",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_comment_application_id"), table_name="application_comment"
    )
    op.drop_table("application_comment")
    # ### end Alembic commands ###
