"""add application assignment

Revision ID: 3a0cc23fe442
Revises: b0e98c2dd68c
Create Date: 2026-07-03 07:26:37.442417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a0cc23fe442"
down_revision: Union[str, Sequence[str], None] = "b0e98c2dd68c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_assignment",
        sa.Column("assignment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "stage",
            postgresql.ENUM(
                "applied",
                "recruiter_screening",
                "behavioral",
                "tech",
                "board_review",
                "offer",
                "hired",
                "rejected",
                "offer_declined",
                "blacklisted",
                name="application_stage_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
            name=op.f("fk_application_assignment_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.user_id"],
            name=op.f("fk_application_assignment_assigned_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.user_id"],
            name=op.f("fk_application_assignment_assignee_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "assignment_id", name=op.f("pk_application_assignment")
        ),
        sa.UniqueConstraint(
            "application_id", "stage", name="uq_application_assignment_app_stage"
        ),
    )
    op.create_index(
        op.f("ix_application_assignment_application_id"),
        "application_assignment",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_assignment_assignee_id"),
        "application_assignment",
        ["assignee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_assignment_assignee_id"),
        table_name="application_assignment",
    )
    op.drop_index(
        op.f("ix_application_assignment_application_id"),
        table_name="application_assignment",
    )
    op.drop_table("application_assignment")
    # ### end Alembic commands ###
