"""add active_run_id to training

Revision ID: 632c0fe034fe
Revises: 9aebcd77b2b4
Create Date: 2026-10-01 03:10:22.412202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "632c0fe034fe"
down_revision: Union[str, Sequence[str], None] = "9aebcd77b2b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("active_run_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "active_run_id")
    # ### end Alembic commands ###
