"""Add length limit to current_stage and time_urgency for MentorshipRoundParticipantsEntity

Revision ID: 7ab80335bdac
Revises: c629f4c873ba
Create Date: 2026-04-28 03:12:30.132056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ab80335bdac"
down_revision: Union[str, Sequence[str], None] = "c629f4c873ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
