"""Make notification type nullable during the expand

Revision ID: 8cb4d2319db5
Revises: 1eed2204a642
Create Date: 2026-08-07 08:01:51.575553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8cb4d2319db5"
down_revision: Union[str, Sequence[str], None] = "1eed2204a642"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notification",
        "type",
        existing_type=postgresql.ENUM(
            "assigned_to_evaluate",
            "mentioned",
            "job_review_requested",
            "job_review_approved",
            "job_review_rejected",
            "application_submitted",
            "application_auto_rejected",
            "application_auto_hired",
            name="notification_type_enum",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notification",
        "type",
        existing_type=postgresql.ENUM(
            "assigned_to_evaluate",
            "mentioned",
            "job_review_requested",
            "job_review_approved",
            "job_review_rejected",
            "application_submitted",
            "application_auto_rejected",
            "application_auto_hired",
            name="notification_type_enum",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
