"""add job_activity table

Revision ID: 938f67fc6602
Revises: fc87aeeec652
Create Date: 2026-07-10 02:41:44.716275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938f67fc6602'
down_revision: Union[str, Sequence[str], None] = 'fc87aeeec652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_activity',
    sa.Column('activity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], name=op.f('fk_job_activity_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], name=op.f('fk_job_activity_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', name=op.f('pk_job_activity'))
    )
    op.create_index(op.f('ix_job_activity_job_id'), 'job_activity', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_activity_job_id'), table_name='job_activity')
    op.drop_table('job_activity')
    # ### end Alembic commands ###
