"""add job config columns

Revision ID: 95b36bb95db2
Revises: fed784dde7d9
Create Date: 2026-06-30 02:44:16.375922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95b36bb95db2"
down_revision: Union[str, Sequence[str], None] = "fed784dde7d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "screen_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "job",
        sa.Column(
            "profile_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "job",
        sa.Column(
            "pending_profile_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "pending_profile_config")
    op.drop_column("job", "profile_config")
    op.drop_column("job", "screen_rules")
    # ### end Alembic commands ###
