"""add mentorship email tables

Revision ID: 9b3d1ba0df5e
Revises: efe7a728a43d
Create Date: 2026-10-09 03:23:59.528426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b3d1ba0df5e"
down_revision: Union[str, Sequence[str], None] = "efe7a728a43d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "draft",
        "preparing",
        "failed",
        "scheduled",
        "sent",
        "aborted",
        "cancelled",
        name="mentorship_email_send_status_enum",
    ).create(op.get_bind())
    sa.Enum(
        "pending",
        "handed_to_kit",
        "unsubscribed",
        "bounced",
        "import_failed",
        name="mentorship_email_recipient_result_enum",
    ).create(op.get_bind())
    op.create_table(
        "mentorship_email_send",
        sa.Column("send_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("kit_draft_id", sa.BigInteger(), nullable=False),
        sa.Column("kit_draft_subject", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "preparing",
                "failed",
                "scheduled",
                "sent",
                "aborted",
                "cancelled",
                name="mentorship_email_send_status_enum",
                create_type=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("sender_address", sa.String(length=255), nullable=False),
        sa.Column("kit_tag_name", sa.String(length=255), nullable=False),
        sa.Column("kit_tag_id", sa.BigInteger(), nullable=True),
        sa.Column("kit_broadcast_id", sa.BigInteger(), nullable=True),
        sa.Column("prepare_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.Column("preview_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("preview_subject", sa.String(length=500), nullable=True),
        sa.Column("preview_html", sa.Text(), nullable=True),
        sa.Column("kit_recipient_count", sa.Integer(), nullable=True),
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tag_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name=op.f("fk_mentorship_email_send_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["mentorship_round.round_id"],
            name=op.f("fk_mentorship_email_send_round_id_mentorship_round"),
        ),
        sa.PrimaryKeyConstraint("send_id", name=op.f("pk_mentorship_email_send")),
    )
    op.create_table(
        "mentorship_email_recipient",
        sa.Column("recipient_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("send_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("kit_subscriber_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "result",
            postgresql.ENUM(
                "pending",
                "handed_to_kit",
                "unsubscribed",
                "bounced",
                "import_failed",
                name="mentorship_email_recipient_result_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["send_id"],
            ["mentorship_email_send.send_id"],
            name=op.f("fk_mentorship_email_recipient_send_id_mentorship_email_send"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_mentorship_email_recipient_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "recipient_id", name=op.f("pk_mentorship_email_recipient")
        ),
        sa.UniqueConstraint(
            "send_id", "user_id", name=op.f("uq_mentorship_email_recipient_send_id")
        ),
    )
    op.create_index(
        op.f("ix_mentorship_email_recipient_send_id"),
        "mentorship_email_recipient",
        ["send_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mentorship_email_recipient_user_id"),
        "mentorship_email_recipient",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_mentorship_email_recipient_user_id"),
        table_name="mentorship_email_recipient",
    )
    op.drop_index(
        op.f("ix_mentorship_email_recipient_send_id"),
        table_name="mentorship_email_recipient",
    )
    op.drop_table("mentorship_email_recipient")
    op.drop_table("mentorship_email_send")
    sa.Enum(
        "pending",
        "handed_to_kit",
        "unsubscribed",
        "bounced",
        "import_failed",
        name="mentorship_email_recipient_result_enum",
    ).drop(op.get_bind())
    sa.Enum(
        "draft",
        "preparing",
        "failed",
        "scheduled",
        "sent",
        "aborted",
        "cancelled",
        name="mentorship_email_send_status_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
