"""add approval_request and mentorship_participant_note

Revision ID: 9e699d638225
Revises: 051306857625
Create Date: 2026-10-07 01:47:33.927207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e699d638225"
down_revision: Union[str, Sequence[str], None] = "051306857625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "status_change", "matching_exemption", name="participant_note_tag_enum"
    ).create(op.get_bind())
    sa.Enum(
        "pending",
        "approved",
        "rejected",
        "withdrawn",
        "superseded",
        name="approval_request_status_enum",
    ).create(op.get_bind())
    op.create_table(
        "approval_request",
        sa.Column("request_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("raised_by", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                "withdrawn",
                "superseded",
                name="approval_request_status_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_comment", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.user_id"],
            name=op.f("fk_approval_request_decided_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["raised_by"],
            ["users.user_id"],
            name=op.f("fk_approval_request_raised_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.user_id"],
            name=op.f("fk_approval_request_reviewer_id_users"),
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_approval_request")),
    )
    op.create_index(
        "ix_approval_request_raised_by_status",
        "approval_request",
        ["raised_by", "status"],
        unique=False,
    )
    op.create_index(
        "ix_approval_request_reviewer_status",
        "approval_request",
        ["reviewer_id", "status"],
        unique=False,
    )
    op.create_index(
        "ux_approval_request_pending_target",
        "approval_request",
        ["action", "target_type", "target_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "mentorship_participant_note",
        sa.Column("note_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=True),
        sa.Column(
            "tag",
            postgresql.ENUM(
                "status_change",
                "matching_exemption",
                name="participant_note_tag_enum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.user_id"],
            name=op.f("fk_mentorship_participant_note_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["mentorship_pairs.pair_id"],
            name=op.f("fk_mentorship_participant_note_pair_id_mentorship_pairs"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["approval_request.request_id"],
            name=op.f("fk_mentorship_participant_note_request_id_approval_request"),
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["mentorship_round.round_id"],
            name=op.f("fk_mentorship_participant_note_round_id_mentorship_round"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_mentorship_participant_note_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("note_id", name=op.f("pk_mentorship_participant_note")),
    )
    op.create_index(
        "ix_mentorship_participant_note_user_round",
        "mentorship_participant_note",
        ["user_id", "round_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_mentorship_participant_note_user_round",
        table_name="mentorship_participant_note",
    )
    op.drop_table("mentorship_participant_note")
    op.drop_index(
        "ux_approval_request_pending_target",
        table_name="approval_request",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_approval_request_reviewer_status", table_name="approval_request")
    op.drop_index("ix_approval_request_raised_by_status", table_name="approval_request")
    op.drop_table("approval_request")
    sa.Enum(
        "pending",
        "approved",
        "rejected",
        "withdrawn",
        "superseded",
        name="approval_request_status_enum",
    ).drop(op.get_bind())
    sa.Enum(
        "status_change", "matching_exemption", name="participant_note_tag_enum"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
