"""drop user_identities.identity_type

Revision ID: b78bd7956d7a
Revises: 99ac7eebad0d
Create Date: 2026-07-22 06:12:42.688591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78bd7956d7a'
down_revision: Union[str, Sequence[str], None] = '99ac7eebad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identities', 'identity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add nullable: the original column was NOT NULL, but a straight
    # add_column(nullable=False) would fail against existing rows with no
    # value to backfill (this column's classification now lives on
    # is_company_email(email_claim), not a value we can safely reconstruct
    # per-row). Nullable is the safe reversible shape.
    op.add_column('user_identities', sa.Column('identity_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
