"""add failed_recipients to email_message

Revision ID: bb4ebd00c402
Revises: 4f68404f9b31
Create Date: 2026-10-02 08:35:07.820484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb4ebd00c402"
down_revision: Union[str, Sequence[str], None] = "4f68404f9b31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_message", sa.Column("failed_recipients", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_message", "failed_recipients")
    # ### end Alembic commands ###
