"""Change timezone of users_entity from enum to varchar

Revision ID: c56ad86a7887
Revises: 52ce4c2a71a4
Create Date: 2026-05-13 05:12:04.770600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c56ad86a7887"
down_revision: Union[str, Sequence[str], None] = "52ce4c2a71a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "timezone",
        existing_type=postgresql.ENUM(
            "America/Los_Angeles",
            "America/New_York",
            "Asia/Shanghai",
            "America/Denver",
            name="user_timezone",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    sa.Enum(
        "America/Los_Angeles",
        "America/New_York",
        "Asia/Shanghai",
        "America/Denver",
        name="user_timezone",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "America/Los_Angeles",
        "America/New_York",
        "Asia/Shanghai",
        "America/Denver",
        name="user_timezone",
    ).create(op.get_bind())
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "America/Los_Angeles",
            "America/New_York",
            "Asia/Shanghai",
            "America/Denver",
            name="user_timezone",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
