"""Add profile_survey to preferences and current_stage/time_urgency to round participants

Revision ID: c629f4c873ba
Revises: 1056efa41572
Create Date: 2026-04-22 08:28:26.203639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c629f4c873ba"
down_revision: Union[str, Sequence[str], None] = "1056efa41572"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mentorship_round_participants",
        sa.Column("current_stage", sa.String(), nullable=True),
    )
    op.add_column(
        "mentorship_round_participants",
        sa.Column("time_urgency", sa.String(), nullable=True),
    )
    op.add_column(
        "preferences",
        sa.Column(
            "profile_survey", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("preferences", "profile_survey")
    op.drop_column("mentorship_round_participants", "time_urgency")
    op.drop_column("mentorship_round_participants", "current_stage")
    # ### end Alembic commands ###
