"""add application_interview table

Adds application_interview: one row per (application_id, stage, round)
recording the Calendar meeting booked for that round (event id, Meet link,
UTC start/end, and who booked it).
Rescheduling updates the row in place; cancelling deletes it outright — the
history lives in application_activity, the same tombstone-free approach
reject/blacklist already use. `stage` reuses the existing
application_stage_enum type (create_type=False — it must not be recreated).

Revision ID: c9cfc7fcaf61
Revises: 156f56629f81
Create Date: 2026-07-29 09:01:50.151255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9cfc7fcaf61"
down_revision: Union[str, Sequence[str], None] = "156f56629f81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_interview",
        sa.Column("interview_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "stage",
            postgresql.ENUM(
                "applied",
                "recruiter_screening",
                "behavioral",
                "tech",
                "board_review",
                "offer",
                "hired",
                "rejected",
                "blacklisted",
                name="application_stage_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("round", sa.Integer(), server_default="1", nullable=False),
        sa.Column("google_event_id", sa.String(), nullable=False),
        sa.Column("meet_link", sa.String(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
            name=op.f("fk_application_interview_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_by"],
            ["users.user_id"],
            name=op.f("fk_application_interview_scheduled_by_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("interview_id", name=op.f("pk_application_interview")),
        sa.UniqueConstraint(
            "application_id",
            "stage",
            "round",
            name="uq_application_interview_app_stage_round",
        ),
    )
    op.create_index(
        op.f("ix_application_interview_application_id"),
        "application_interview",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_application_interview_application_id"),
        table_name="application_interview",
    )
    op.drop_table("application_interview")
    # ### end Alembic commands ###
