"""drop block_request

Revision ID: d30c798152d9
Revises: d5c03a74256f
Create Date: 2026-10-07 07:44:32.671757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d30c798152d9"
down_revision: Union[str, Sequence[str], None] = "d5c03a74256f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("block_request")
    sa.Enum(
        "pending",
        "approved",
        "rejected",
        "superseded",
        name="block_request_status_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "pending",
        "approved",
        "rejected",
        "superseded",
        name="block_request_status_enum",
    ).create(op.get_bind())
    op.create_table(
        "block_request",
        sa.Column("request_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("target_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("raised_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "raised_from", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("reviewer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                "superseded",
                name="block_request_status_enum",
                create_type=False,
            ),
            server_default=sa.text("'pending'::block_request_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("decided_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "decided_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("decision_note", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.user_id"],
            name=op.f("fk_block_request_decided_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["raised_by"],
            ["users.user_id"],
            name=op.f("fk_block_request_raised_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.user_id"],
            name=op.f("fk_block_request_reviewer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.user_id"],
            name=op.f("fk_block_request_target_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_block_request")),
    )
    # ### end Alembic commands ###
