"""drop job_review

Revision ID: d5c03a74256f
Revises: 9e699d638225
Create Date: 2026-10-07 05:39:47.603843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5c03a74256f"
down_revision: Union[str, Sequence[str], None] = "9e699d638225"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_review")
    sa.Enum("pending", "approved", "rejected", name="job_review_status_enum").drop(
        op.get_bind()
    )
    sa.Enum("initial", "revision", "close", "reopen", name="job_review_kind_enum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "initial", "revision", "close", "reopen", name="job_review_kind_enum"
    ).create(op.get_bind())
    sa.Enum("pending", "approved", "rejected", name="job_review_status_enum").create(
        op.get_bind()
    )
    op.create_table(
        "job_review",
        sa.Column("review_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("submitted_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("reviewer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                name="job_review_status_enum",
                create_type=False,
            ),
            server_default=sa.text("'pending'::job_review_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "initial",
                "revision",
                "close",
                "reopen",
                name="job_review_kind_enum",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("submit_message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("reject_comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "decided_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.job_id"], name=op.f("fk_job_review_job_id_job")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.user_id"],
            name=op.f("fk_job_review_reviewer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.user_id"],
            name=op.f("fk_job_review_submitted_by_users"),
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_job_review")),
    )
    # ### end Alembic commands ###
