"""Add user_identities and user_emails tables

Revision ID: dee5e8b0c892
Revises: c56ad86a7887
Create Date: 2026-05-28 08:30:02.487909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dee5e8b0c892"
down_revision: Union[str, Sequence[str], None] = "c56ad86a7887"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_emails",
        sa.Column("email_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("otp_confirmed", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_primary OR otp_confirmed",
            name=op.f("ck_user_emails_user_emails_primary_must_be_confirmed"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_user_emails_user_id_users")
        ),
        sa.PrimaryKeyConstraint("email_id", name=op.f("pk_user_emails")),
        sa.UniqueConstraint("user_id", "email", name="uq_user_emails_user_id_email"),
    )
    op.create_index("user_emails_email_idx", "user_emails", ["email"], unique=False)
    op.create_index(
        "user_emails_primary_idx",
        "user_emails",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "user_identities",
        sa.Column("identity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject_identifier", sa.String(length=255), nullable=False),
        sa.Column("identity_type", sa.String(length=32), nullable=False),
        sa.Column("email_claim", sa.String(length=255), nullable=True),
        sa.Column(
            "linked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_user_identities_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("identity_id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "subject_identifier", name=op.f("uq_user_identities_subject_identifier")
        ),
    )
    op.create_index(
        "user_identities_email_claim_idx",
        "user_identities",
        ["email_claim"],
        unique=False,
    )
    op.create_index(
        "user_identities_user_id_idx", "user_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_identities_user_id_idx", table_name="user_identities")
    op.drop_index("user_identities_email_claim_idx", table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(
        "user_emails_primary_idx",
        table_name="user_emails",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index("user_emails_email_idx", table_name="user_emails")
    op.drop_table("user_emails")
    # ### end Alembic commands ###
