"""drop leave_request decision columns

Revision ID: e1c305f5fd04
Revises: d30c798152d9
Create Date: 2026-10-08 01:16:26.374026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1c305f5fd04"
down_revision: Union[str, Sequence[str], None] = "d30c798152d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_leave_request_decided_by_users"), "leave_request", type_="foreignkey"
    )
    op.drop_column("leave_request", "decided_by")
    op.drop_column("leave_request", "decided_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leave_request",
        sa.Column(
            "decided_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "leave_request",
        sa.Column("decided_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_leave_request_decided_by_users"),
        "leave_request",
        "users",
        ["decided_by"],
        ["user_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
