"""add inbox columns

Revision ID: efe7a728a43d
Revises: e1c305f5fd04
Create Date: 2026-10-08 01:23:57.932971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "efe7a728a43d"
down_revision: Union[str, Sequence[str], None] = "e1c305f5fd04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_message", sa.Column("inbound_kind", sa.String(), nullable=True)
    )
    op.add_column(
        "email_message",
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "email_thread",
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "email_thread", sa.Column("archived_by_user_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "email_thread", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        op.f("fk_email_thread_archived_by_user_id_users"),
        "email_thread",
        "users",
        ["archived_by_user_id"],
        ["user_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_email_thread_archived_by_user_id_users"),
        "email_thread",
        type_="foreignkey",
    )
    op.alter_column(
        "email_thread", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("email_thread", "archived_by_user_id")
    op.drop_column("email_thread", "archived_at")
    op.drop_column("email_message", "attachments")
    op.drop_column("email_message", "inbound_kind")
    # ### end Alembic commands ###
