"""add no_show and red_flag note tags

Revision ID: f2b3354b3118
Revises: 63158db8a00a
Create Date: 2026-10-09 08:26:39.765746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "f2b3354b3118"
down_revision: Union[str, Sequence[str], None] = "63158db8a00a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "participant_note_tag_enum",
        ["status_change", "matching_exemption", "no_show", "red_flag"],
        [
            TableReference(
                table_schema="public",
                table_name="mentorship_participant_note",
                column_name="tag",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "participant_note_tag_enum",
        ["status_change", "matching_exemption"],
        [
            TableReference(
                table_schema="public",
                table_name="mentorship_participant_note",
                column_name="tag",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
