"""add notification table

Revision ID: fc87aeeec652
Revises: 9f4a1c7e2b53
Create Date: 2026-07-09 05:42:33.034220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc87aeeec652"
down_revision: Union[str, Sequence[str], None] = "9f4a1c7e2b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "assigned_to_evaluate",
        "mentioned",
        "job_review_requested",
        "job_review_approved",
        "job_review_rejected",
        name="notification_type_enum",
    ).create(op.get_bind())
    op.create_table(
        "notification",
        sa.Column("notification_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "assigned_to_evaluate",
                "mentioned",
                "job_review_requested",
                "job_review_approved",
                "job_review_rejected",
                name="notification_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=True),
        sa.Column("comment_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("job_review_id", sa.Integer(), nullable=True),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.user_id"],
            name=op.f("fk_notification_actor_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.application_id"],
            name=op.f("fk_notification_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["application_comment.comment_id"],
            name=op.f("fk_notification_comment_id_application_comment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.job_id"],
            name=op.f("fk_notification_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_review_id"],
            ["job_review.review_id"],
            name=op.f("fk_notification_job_review_id_job_review"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_notification_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("notification_id", name=op.f("pk_notification")),
    )
    op.create_index(
        op.f("ix_notification_application_id"),
        "notification",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_job_id"), "notification", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_user_id"), "notification", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_user_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_job_id"), table_name="notification")
    op.drop_index(op.f("ix_notification_application_id"), table_name="notification")
    op.drop_table("notification")
    sa.Enum(
        "assigned_to_evaluate",
        "mentioned",
        "job_review_requested",
        "job_review_approved",
        "job_review_rejected",
        name="notification_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
