"""add recruiting job and job_review schema

Revision ID: fed784dde7d9
Revises: f3d9a2b6c8e1
Create Date: 2026-06-27 08:22:42.640516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fed784dde7d9"
down_revision: Union[str, Sequence[str], None] = "f3d9a2b6c8e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "initial", "revision", "close", "reopen", name="job_review_kind_enum"
    ).create(op.get_bind())
    sa.Enum("pending", "approved", "rejected", name="job_review_status_enum").create(
        op.get_bind()
    )
    sa.Enum(
        "draft",
        "pending_review",
        "published",
        "closed",
        "published_pending_revision",
        "pending_close",
        "pending_reopen",
        name="job_status_enum",
    ).create(op.get_bind())
    sa.Enum("mentor", "mentee", name="job_mentorship_role_enum").create(op.get_bind())
    sa.Enum("employment", "activity", name="job_kind_enum").create(op.get_bind())
    op.create_table(
        "job",
        sa.Column("job_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "employment", "activity", name="job_kind_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "mentorship_role",
            postgresql.ENUM(
                "mentor", "mentee", name="job_mentorship_role_enum", create_type=False
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft",
                "pending_review",
                "published",
                "closed",
                "published_pending_revision",
                "pending_close",
                "pending_reopen",
                name="job_status_enum",
                create_type=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "form_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "pipeline_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "pending_form_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "pending_pipeline_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "was_published",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_job")),
    )
    op.create_table(
        "job_review",
        sa.Column("review_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "approved",
                "rejected",
                name="job_review_status_enum",
                create_type=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "initial",
                "revision",
                "close",
                "reopen",
                name="job_review_kind_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("submit_message", sa.String(), nullable=True),
        sa.Column("reject_comment", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.job_id"], name=op.f("fk_job_review_job_id_job")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.user_id"],
            name=op.f("fk_job_review_reviewer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.user_id"],
            name=op.f("fk_job_review_submitted_by_users"),
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_job_review")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_review")
    op.drop_table("job")
    sa.Enum("employment", "activity", name="job_kind_enum").drop(op.get_bind())
    sa.Enum("mentor", "mentee", name="job_mentorship_role_enum").drop(op.get_bind())
    sa.Enum(
        "draft",
        "pending_review",
        "published",
        "closed",
        "published_pending_revision",
        "pending_close",
        "pending_reopen",
        name="job_status_enum",
    ).drop(op.get_bind())
    sa.Enum("pending", "approved", "rejected", name="job_review_status_enum").drop(
        op.get_bind()
    )
    sa.Enum("initial", "revision", "close", "reopen", name="job_review_kind_enum").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
