load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "user_identity_service",
    srcs = ["user_identity_service.py"],
    deps = ["//backend/entity:entities"],
)
