load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "google_chat_consumer_test",
    srcs = ["google_chat_consumer_test.py"],
    deps = [
        "//src/consumers:google_chat_consumer",
    ],
)
