load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "microsoft_service_test",
    srcs = ["microsoft_service_test.py"],
    deps = [
        "//src/service:microsoft_service",
    ],
)
