load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "google_calendar_history_fetcher_test",
    srcs = ["google_calendar_history_fetcher_test.py"],
    deps = [
        "//src/historical_data:google_calendar_history_fetcher",
    ],
)
