load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "environment_constants",
    srcs = ["environment_constants.py"],
)

py_library(
    name = "logger",
    srcs = ["logger.py"],
    deps = ["//src/common:environment_constants"],
)
