LOG_LEVEL = "LOG_LEVEL"
USER_EMAIL = "USER_EMAIL"
SERVICE_ACCOUNT_EMAIL = "SERVICE_ACCOUNT_EMAIL"
ADMIN_EMAIL = "ADMIN_EMAIL"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_PASSWORD = "REDIS_PASSWORD"

GERRIT_URL = "GERRIT_URL"
GERRIT_USER = "GERRIT_USER"
GERRIT_HTTP_PASS = "GERRIT_HTTP_PASS"

AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
AZURE_TENANT_ID = "AZURE_TENANT_ID"

JIRA_SERVER = "JIRA_SERVER"
JIRA_USER = "JIRA_USER"
JIRA_PASSWORD = "JIRA_PASSWORD"

MICROSOFT_ADMIN_LDAP = "MICROSFT_ADMIN_LDAP"
MICROSOFT_USER_LDAP = "MICROSFT_USER_LDAP"
